version: "3"
services:
    strapi:
        container_name: strapi
        build:
            context: .
        restart: unless-stopped
        env_file: .env
        ports:
            - "1337:1337"
